name: PHP Project CI/CD

on:
  workflow_dispatch:

jobs:
  php-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Ajuste para a versão do PHP que está usando
        extensions: mbstring, pdo, json

    - name: Install Dependencies
      run: |
        if [ -f "composer.json" ]; then
          composer install --no-interaction --prefer-dist
        fi

    - name: Execute Tests via PHPUnit
      run: |
        ./vendor/bin/phpunit tests  # Caso use o Composer para instalar o PHPUnit
