name: PHP Project CI/CD

on:
  workflow_dispatch:

jobs:
  php-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: cadastropedkids
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Dependencies
        run: |
          if [ -f "composer.json" ]; then
            composer install --no-interaction --prefer-dist
          fi

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h"localhost" --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 2
          done

      - name: Run Tests
        run: |
          ./vendor/bin/phpunit tests
