name: PHP Project CI/CD

on:
  workflow_dispatch:

jobs:
  php-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: cadastropedkids
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install PHPUnit
        run: |
          composer require --dev phpunit/phpunit ^9
      
      - name: Install Composer dependencies
        run: |
          composer install --no-interaction --prefer-dist

      - name: Wait for MySQL
        run: |
            echo "Waiting for MySQL to be ready..."
            for i in {1..15}; do  # Tentativas aumentadas para 15
              # Tenta verificar a conexão via mysqladmin ping
              if mysqladmin -h "localhost" --user=root --password=root ping --silent; then
                echo "MySQL is ready"
                break
              fi
              echo "Waiting for MySQL to be ready... Attempt $i"
              sleep 2  # Aguardar 2 segundos antes de tentar novamente
            done
        
      - name: Run Tests
        run: ./vendor/bin/phpunit --filter CadastroTest
